use std::io::Result;

fn main() -> Result<()> {
    prost_build::Config::new().compile_protos(
        &[
            // "protos/k8s.io/api/admissionregistration/v1beta1/generated.proto",
            // "protos/k8s.io/api/admissionregistration/v1/generated.proto",
            // "protos/k8s.io/api/admission/v1beta1/generated.proto",
            // "protos/k8s.io/api/admission/v1/generated.proto",
            // "protos/k8s.io/api/apiserverinternal/v1alpha1/generated.proto",
            // "protos/k8s.io/api/apps/v1beta1/generated.proto",
            // "protos/k8s.io/api/apps/v1beta2/generated.proto",
            // "protos/k8s.io/api/apps/v1/generated.proto",
            // "protos/k8s.io/api/authentication/v1beta1/generated.proto",
            // "protos/k8s.io/api/authentication/v1/generated.proto",
            // "protos/k8s.io/api/authorization/v1beta1/generated.proto",
            // "protos/k8s.io/api/authorization/v1/generated.proto",
            // "protos/k8s.io/api/autoscaling/v1/generated.proto",
            // "protos/k8s.io/api/autoscaling/v2beta1/generated.proto",
            // "protos/k8s.io/api/autoscaling/v2beta2/generated.proto",
            // "protos/k8s.io/api/batch/v1beta1/generated.proto",
            // "protos/k8s.io/api/batch/v1/generated.proto",
            // "protos/k8s.io/api/certificates/v1beta1/generated.proto",
            // "protos/k8s.io/api/certificates/v1/generated.proto",
            // "protos/k8s.io/api/coordination/v1beta1/generated.proto",
            // "protos/k8s.io/api/coordination/v1/generated.proto",
            "protos/k8s.io/api/core/v1/generated.proto",
            // "protos/k8s.io/api/discovery/v1beta1/generated.proto",
            // "protos/k8s.io/api/discovery/v1/generated.proto",
            // "protos/k8s.io/api/events/v1beta1/generated.proto",
            // "protos/k8s.io/api/events/v1/generated.proto",
            // "protos/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto",
            // "protos/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto",
            // "protos/k8s.io/api/extensions/v1beta1/generated.proto",
            // "protos/k8s.io/api/flowcontrol/v1alpha1/generated.proto",
            // "protos/k8s.io/api/flowcontrol/v1beta1/generated.proto",
            // "protos/k8s.io/api/imagepolicy/v1alpha1/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/api/resource/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/apis/meta/v1beta1/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/apis/testapigroup/v1/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/runtime/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/runtime/schema/generated.proto",
            // "protos/k8s.io/apimachinery/pkg/util/intstr/generated.proto",
            // "protos/k8s.io/api/networking/v1beta1/generated.proto",
            // "protos/k8s.io/api/networking/v1/generated.proto",
            // "protos/k8s.io/api/node/v1alpha1/generated.proto",
            // "protos/k8s.io/api/node/v1beta1/generated.proto",
            // "protos/k8s.io/api/node/v1/generated.proto",
            // "protos/k8s.io/api/policy/v1beta1/generated.proto",
            // "protos/k8s.io/api/policy/v1/generated.proto",
            // "protos/k8s.io/api/rbac/v1alpha1/generated.proto",
            // "protos/k8s.io/api/rbac/v1beta1/generated.proto",
            // "protos/k8s.io/api/rbac/v1/generated.proto",
            // "protos/k8s.io/api/scheduling/v1alpha1/generated.proto",
            // "protos/k8s.io/api/scheduling/v1beta1/generated.proto",
            // "protos/k8s.io/api/scheduling/v1/generated.proto",
            // "protos/k8s.io/api/storage/v1alpha1/generated.proto",
            // "protos/k8s.io/api/storage/v1beta1/generated.proto",
            // "protos/k8s.io/api/storage/v1/generated.proto",
            // "protos/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1beta1/generated.proto",
            // "protos/k8s.io/kube-aggregator/pkg/apis/apiregistration/v1/generated.proto",
            // "protos/k8s.io/metrics/pkg/apis/custom_metrics/v1beta1/generated.proto",
            // "protos/k8s.io/metrics/pkg/apis/custom_metrics/v1beta2/generated.proto",
            // "protos/k8s.io/metrics/pkg/apis/external_metrics/v1beta1/generated.proto",
            // "protos/k8s.io/metrics/pkg/apis/metrics/v1alpha1/generated.proto",
            // "protos/k8s.io/metrics/pkg/apis/metrics/v1beta1/generated.proto",
        ],
        &["protos/"],
    )?;
    // Generate code in `src/` by reading files in `OUT_DIR`?
    // Need to create `mod.rs` file for each level based on the filename, and write generated code in correct file.
    Ok(())
}
