// This file is @generated by prost-build.
/// BasicSchedulingPolicy indicates that standard Kubernetes
/// scheduling behavior should be used.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BasicSchedulingPolicy {}
/// GangSchedulingPolicy defines the parameters for gang scheduling.
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GangSchedulingPolicy {
    /// MinCount is the minimum number of pods that must be schedulable or scheduled
    /// at the same time for the scheduler to admit the entire group.
    /// It must be a positive integer.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:minimum=1
    #[prost(int32, optional, tag = "1")]
    pub min_count: ::core::option::Option<i32>,
}
/// PodGroup represents a runtime instance of pods grouped together.
/// PodGroups are created by workload controllers (Job, LWS, JobSet, etc...) from
/// Workload.podGroupTemplates.
/// PodGroup API enablement is toggled by the GenericWorkload feature gate.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodGroup {
    /// Standard object's metadata.
    /// More info: <https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata>
    ///
    /// +optional
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<super::super::super::apimachinery::pkg::apis::meta::v1::ObjectMeta>,
    /// Spec defines the desired state of the PodGroup.
    ///
    /// +required
    #[prost(message, optional, tag = "2")]
    pub spec: ::core::option::Option<PodGroupSpec>,
    /// Status represents the current observed state of the PodGroup.
    ///
    /// +optional
    #[prost(message, optional, tag = "3")]
    pub status: ::core::option::Option<PodGroupStatus>,
}
/// PodGroupList contains a list of PodGroup resources.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodGroupList {
    /// Standard list metadata.
    ///
    /// +optional
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<super::super::super::apimachinery::pkg::apis::meta::v1::ListMeta>,
    /// Items is the list of PodGroups.
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<PodGroup>,
}
/// PodGroupResourceClaim references exactly one ResourceClaim, either directly
/// or by naming a ResourceClaimTemplate which is then turned into a ResourceClaim
/// for the PodGroup.
///
/// It adds a name to it that uniquely identifies the ResourceClaim inside the PodGroup.
/// Pods that need access to the ResourceClaim define a matching reference in its
/// own Spec.ResourceClaims. The Pod's claim must match all fields of the
/// PodGroup's claim exactly.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PodGroupResourceClaim {
    /// Name uniquely identifies this resource claim inside the PodGroup.
    /// This must be a DNS_LABEL.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-short-name
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// ResourceClaimName is the name of a ResourceClaim object in the same
    /// namespace as this PodGroup. The ResourceClaim will be reserved for the
    /// PodGroup instead of its individual pods.
    ///
    /// Exactly one of ResourceClaimName and ResourceClaimTemplateName must
    /// be set.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:unionMember
    /// +k8s:format=k8s-long-name
    #[prost(string, optional, tag = "2")]
    pub resource_claim_name: ::core::option::Option<::prost::alloc::string::String>,
    /// ResourceClaimTemplateName is the name of a ResourceClaimTemplate
    /// object in the same namespace as this PodGroup.
    ///
    /// The template will be used to create a new ResourceClaim, which will
    /// be bound to this PodGroup. When this PodGroup is deleted, the ResourceClaim
    /// will also be deleted. The PodGroup name and resource name, along with a
    /// generated component, will be used to form a unique name for the
    /// ResourceClaim, which will be recorded in podgroup.status.resourceClaimStatuses.
    ///
    /// This field is immutable and no changes will be made to the
    /// corresponding ResourceClaim by the control plane after creating the
    /// ResourceClaim.
    ///
    /// Exactly one of ResourceClaimName and ResourceClaimTemplateName must
    /// be set.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:unionMember
    /// +k8s:format=k8s-long-name
    #[prost(string, optional, tag = "3")]
    pub resource_claim_template_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// PodGroupResourceClaimStatus is stored in the PodGroupStatus for each
/// PodGroupResourceClaim which references a ResourceClaimTemplate. It stores the
/// generated name for the corresponding ResourceClaim.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PodGroupResourceClaimStatus {
    /// Name uniquely identifies this resource claim inside the PodGroup. This
    /// must match the name of an entry in podgroup.spec.resourceClaims, which
    /// implies that the string must be a DNS_LABEL.
    ///
    /// +required
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// ResourceClaimName is the name of the ResourceClaim that was generated for
    /// the PodGroup in the namespace of the PodGroup. If this is unset, then
    /// generating a ResourceClaim was not necessary. The
    /// podgroup.spec.resourceClaims entry can be ignored in this case.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:format=k8s-long-name
    #[prost(string, optional, tag = "2")]
    pub resource_claim_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// PodGroupSchedulingConstraints defines scheduling constraints (e.g. topology) for a PodGroup.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodGroupSchedulingConstraints {
    /// Topology defines the topology constraints for the pod group.
    /// Currently only a single topology constraint can be specified. This may change in the future.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:maxItems=1
    /// +listType=atomic
    /// +k8s:listType=atomic
    #[prost(message, repeated, tag = "1")]
    pub topology: ::prost::alloc::vec::Vec<TopologyConstraint>,
}
/// PodGroupSchedulingPolicy defines the scheduling configuration for a PodGroup.
/// Exactly one policy must be set.
/// +union
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PodGroupSchedulingPolicy {
    /// Basic specifies that the pods in this group should be scheduled using
    /// standard Kubernetes scheduling behavior.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:unionMember
    #[prost(message, optional, tag = "1")]
    pub basic: ::core::option::Option<BasicSchedulingPolicy>,
    /// Gang specifies that the pods in this group should be scheduled using
    /// all-or-nothing semantics.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:unionMember
    #[prost(message, optional, tag = "2")]
    pub gang: ::core::option::Option<GangSchedulingPolicy>,
}
/// PodGroupSpec defines the desired state of a PodGroup.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodGroupSpec {
    /// PodGroupTemplateRef references an optional PodGroup template within other object
    /// (e.g. Workload) that was used to create the PodGroup. This field is immutable.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:immutable
    #[prost(message, optional, tag = "1")]
    pub pod_group_template_ref: ::core::option::Option<PodGroupTemplateReference>,
    /// SchedulingPolicy defines the scheduling policy for this instance of the PodGroup.
    /// Controllers are expected to fill this field by copying it from a PodGroupTemplate.
    /// This field is immutable.
    ///
    /// +required
    /// +k8s:immutable
    #[prost(message, optional, tag = "2")]
    pub scheduling_policy: ::core::option::Option<PodGroupSchedulingPolicy>,
    /// SchedulingConstraints defines optional scheduling constraints (e.g. topology) for this PodGroup.
    /// Controllers are expected to fill this field by copying it from a PodGroupTemplate.
    /// This field is immutable.
    /// This field is only available when the TopologyAwareWorkloadScheduling feature gate is enabled.
    ///
    /// +featureGate=TopologyAwareWorkloadScheduling
    /// +optional
    /// +k8s:ifDisabled(TopologyAwareWorkloadScheduling)=+k8s:forbidden
    /// +k8s:ifEnabled(TopologyAwareWorkloadScheduling)=+k8s:optional
    /// +k8s:ifEnabled(TopologyAwareWorkloadScheduling)=+k8s:immutable
    #[prost(message, optional, tag = "3")]
    pub scheduling_constraints: ::core::option::Option<PodGroupSchedulingConstraints>,
    /// ResourceClaims defines which ResourceClaims may be shared among Pods in
    /// the group. Pods consume the devices allocated to a PodGroup's claim by
    /// defining a claim in its own Spec.ResourceClaims that matches the
    /// PodGroup's claim exactly. The claim must have the same name and refer to
    /// the same ResourceClaim or ResourceClaimTemplate.
    ///
    /// This is an alpha-level field and requires that the
    /// DRAWorkloadResourceClaims feature gate is enabled.
    ///
    /// This field is immutable.
    ///
    /// +optional
    /// +patchMergeKey=name
    /// +patchStrategy=merge,retainKeys
    /// +listType=map
    /// +listMapKey=name
    /// +k8s:optional
    /// +k8s:listType=map
    /// +k8s:listMapKey=name
    /// +k8s:maxItems=4
    /// +k8s:immutable
    /// +featureGate=DRAWorkloadResourceClaims
    #[prost(message, repeated, tag = "4")]
    pub resource_claims: ::prost::alloc::vec::Vec<PodGroupResourceClaim>,
    /// DisruptionMode defines the mode in which a given PodGroup can be disrupted.
    /// Controllers are expected to fill this field by copying it from a PodGroupTemplate.
    /// One of Pod, PodGroup. Defaults to Pod if unset.
    /// This field is immutable.
    /// This field is available only when the WorkloadAwarePreemption feature gate
    /// is enabled.
    ///
    /// +featureGate=WorkloadAwarePreemption
    /// +optional
    /// +k8s:ifDisabled("WorkloadAwarePreemption")=+k8s:forbidden
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:optional
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:immutable
    /// +default="Pod"
    #[prost(string, optional, tag = "5")]
    pub disruption_mode: ::core::option::Option<::prost::alloc::string::String>,
    /// PriorityClassName defines the priority that should be considered when scheduling this pod group.
    /// Controllers are expected to fill this field by copying it from a PodGroupTemplate.
    /// Otherwise, it is validated and resolved similarly to the PriorityClassName on PodGroupTemplate
    /// (i.e. if no priority class is specified, admission control can set this to the global default
    /// priority class if it exists. Otherwise, the pod group's priority will be zero).
    /// This field is immutable.
    /// This field is available only when the WorkloadAwarePreemption feature gate
    /// is enabled.
    ///
    /// +featureGate=WorkloadAwarePreemption
    /// +optional
    /// +k8s:ifDisabled("WorkloadAwarePreemption")=+k8s:forbidden
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:optional
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:format=k8s-long-name
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:immutable
    #[prost(string, optional, tag = "6")]
    pub priority_class_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Priority is the value of priority of this pod group. Various system components
    /// use this field to find the priority of the pod group. When Priority Admission
    /// Controller is enabled, it prevents users from setting this field. The admission
    /// controller populates this field from PriorityClassName.
    /// The higher the value, the higher the priority.
    /// This field is immutable.
    /// This field is available only when the WorkloadAwarePreemption feature gate
    /// is enabled.
    ///
    /// +featureGate=WorkloadAwarePreemption
    /// +optional
    /// +k8s:ifDisabled("WorkloadAwarePreemption")=+k8s:forbidden
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:optional
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:immutable
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:maximum=1000000000 # HighestUserDefinablePriority
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:minimum=-2147483648
    #[prost(int32, optional, tag = "7")]
    pub priority: ::core::option::Option<i32>,
}
/// PodGroupStatus represents information about the status of a pod group.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodGroupStatus {
    /// Conditions represent the latest observations of the PodGroup's state.
    ///
    /// Known condition types:
    /// - "PodGroupScheduled": Indicates whether the scheduling requirement has been satisfied.
    /// - "DisruptionTarget": Indicates whether the PodGroup is about to be terminated
    ///    due to disruption such as preemption.
    ///
    /// Known reasons for the PodGroupScheduled condition:
    /// - "Unschedulable": The PodGroup cannot be scheduled due to resource constraints,
    ///    affinity/anti-affinity rules, or insufficient capacity for the gang.
    /// - "SchedulerError": The PodGroup cannot be scheduled due to some internal error
    ///    that happened during scheduling, for example due to nodeAffinity parsing errors.
    ///
    /// Known reasons for the DisruptionTarget condition:
    /// - "PreemptionByScheduler": The PodGroup was preempted by the scheduler to make room for
    ///    higher-priority PodGroups or Pods.
    ///
    /// +optional
    /// +patchMergeKey=type
    /// +patchStrategy=merge
    /// +listType=map
    /// +listMapKey=type
    #[prost(message, repeated, tag = "1")]
    pub conditions:
        ::prost::alloc::vec::Vec<super::super::super::apimachinery::pkg::apis::meta::v1::Condition>,
    /// Status of resource claims.
    /// +optional
    /// +patchMergeKey=name
    /// +patchStrategy=merge,retainKeys
    /// +listType=map
    /// +listMapKey=name
    /// +k8s:optional
    /// +k8s:listType=map
    /// +k8s:listMapKey=name
    /// +k8s:maxItems=4
    /// +featureGate=DRAWorkloadResourceClaims
    #[prost(message, repeated, tag = "2")]
    pub resource_claim_statuses: ::prost::alloc::vec::Vec<PodGroupResourceClaimStatus>,
}
/// PodGroupTemplate represents a template for a set of pods with a scheduling policy.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PodGroupTemplate {
    /// Name is a unique identifier for the PodGroupTemplate within the Workload.
    /// It must be a DNS label. This field is immutable.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-short-name
    #[prost(string, optional, tag = "1")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
    /// SchedulingPolicy defines the scheduling policy for this PodGroupTemplate.
    ///
    /// +required
    #[prost(message, optional, tag = "2")]
    pub scheduling_policy: ::core::option::Option<PodGroupSchedulingPolicy>,
    /// SchedulingConstraints defines optional scheduling constraints (e.g. topology) for this PodGroupTemplate.
    /// This field is only available when the TopologyAwareWorkloadScheduling feature gate is enabled.
    ///
    /// +featureGate=TopologyAwareWorkloadScheduling
    /// +optional
    /// +k8s:ifDisabled(TopologyAwareWorkloadScheduling)=+k8s:forbidden
    /// +k8s:ifEnabled(TopologyAwareWorkloadScheduling)=+k8s:optional
    #[prost(message, optional, tag = "3")]
    pub scheduling_constraints: ::core::option::Option<PodGroupSchedulingConstraints>,
    /// ResourceClaims defines which ResourceClaims may be shared among Pods in
    /// the group. Pods consume the devices allocated to a PodGroup's claim by
    /// defining a claim in its own Spec.ResourceClaims that matches the
    /// PodGroup's claim exactly. The claim must have the same name and refer to
    /// the same ResourceClaim or ResourceClaimTemplate.
    ///
    /// This is an alpha-level field and requires that the
    /// DRAWorkloadResourceClaims feature gate is enabled.
    ///
    /// This field is immutable.
    ///
    /// +optional
    /// +patchMergeKey=name
    /// +patchStrategy=merge,retainKeys
    /// +listType=map
    /// +listMapKey=name
    /// +k8s:optional
    /// +k8s:listType=map
    /// +k8s:listMapKey=name
    /// +k8s:maxItems=4
    /// +k8s:immutable
    /// +featureGate=DRAWorkloadResourceClaims
    #[prost(message, repeated, tag = "4")]
    pub resource_claims: ::prost::alloc::vec::Vec<PodGroupResourceClaim>,
    /// DisruptionMode defines the mode in which a given PodGroup can be disrupted.
    /// One of Pod, PodGroup.
    /// This field is available only when the WorkloadAwarePreemption feature gate
    /// is enabled.
    ///
    /// +featureGate=WorkloadAwarePreemption
    /// +optional
    /// +k8s:ifDisabled("WorkloadAwarePreemption")=+k8s:forbidden
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:optional
    #[prost(string, optional, tag = "5")]
    pub disruption_mode: ::core::option::Option<::prost::alloc::string::String>,
    /// PriorityClassName indicates the priority that should be considered when scheduling
    /// a pod group created from this template. If no priority class is specified, admission
    /// control can set this to the global default priority class if it exists. Otherwise,
    /// pod groups created from this template will have the priority set to zero.
    /// This field is available only when the WorkloadAwarePreemption feature gate
    /// is enabled.
    ///
    /// +featureGate=WorkloadAwarePreemption
    /// +optional
    /// +k8s:ifDisabled("WorkloadAwarePreemption")=+k8s:forbidden
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:optional
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:format=k8s-long-name
    #[prost(string, optional, tag = "6")]
    pub priority_class_name: ::core::option::Option<::prost::alloc::string::String>,
    /// Priority is the value of priority of pod groups created from this template. Various
    /// system components use this field to find the priority of the pod group. When
    /// Priority Admission Controller is enabled, it prevents users from setting this field.
    /// The admission controller populates this field from PriorityClassName.
    /// The higher the value, the higher the priority.
    /// This field is available only when the WorkloadAwarePreemption feature gate
    /// is enabled.
    ///
    /// +featureGate=WorkloadAwarePreemption
    /// +optional
    /// +k8s:ifDisabled("WorkloadAwarePreemption")=+k8s:forbidden
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:optional
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:maximum=1000000000 # HighestUserDefinablePriority
    /// +k8s:ifEnabled("WorkloadAwarePreemption")=+k8s:minimum=-2147483648
    #[prost(int32, optional, tag = "7")]
    pub priority: ::core::option::Option<i32>,
}
/// PodGroupTemplateReference references a PodGroup template defined in some object (e.g. Workload).
/// Exactly one reference must be set.
/// +union
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PodGroupTemplateReference {
    /// Workload references the PodGroupTemplate within the Workload object that was used to create
    /// the PodGroup.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:unionMember
    #[prost(message, optional, tag = "1")]
    pub workload: ::core::option::Option<WorkloadPodGroupTemplateReference>,
}
/// TopologyConstraint defines a topology constraint for a PodGroup.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TopologyConstraint {
    /// Key specifies the key of the node label representing the topology domain.
    /// All pods within the PodGroup must be colocated within the same domain instance.
    /// Different PodGroups can land on different domain instances even if they derive from the same PodGroupTemplate.
    /// Examples: "topology.kubernetes.io/rack"
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-label-key
    #[prost(string, optional, tag = "1")]
    pub key: ::core::option::Option<::prost::alloc::string::String>,
}
/// TypedLocalObjectReference allows to reference typed object inside the same namespace.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TypedLocalObjectReference {
    /// APIGroup is the group for the resource being referenced.
    /// If APIGroup is empty, the specified Kind must be in the core API group.
    /// For any other third-party types, setting APIGroup is required.
    /// It must be a DNS subdomain.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:format=k8s-long-name
    #[prost(string, optional, tag = "1")]
    pub api_group: ::core::option::Option<::prost::alloc::string::String>,
    /// Kind is the type of resource being referenced.
    /// It must be a path segment name.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-path-segment-name
    #[prost(string, optional, tag = "2")]
    pub kind: ::core::option::Option<::prost::alloc::string::String>,
    /// Name is the name of resource being referenced.
    /// It must be a path segment name.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-path-segment-name
    #[prost(string, optional, tag = "3")]
    pub name: ::core::option::Option<::prost::alloc::string::String>,
}
/// Workload allows for expressing scheduling constraints that should be used
/// when managing the lifecycle of workloads from the scheduling perspective,
/// including scheduling, preemption, eviction and other phases.
/// Workload API enablement is toggled by the GenericWorkload feature gate.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Workload {
    /// Standard object's metadata.
    /// More info: <https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#metadata>
    ///
    /// +optional
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<super::super::super::apimachinery::pkg::apis::meta::v1::ObjectMeta>,
    /// Spec defines the desired behavior of a Workload.
    ///
    /// +required
    #[prost(message, optional, tag = "2")]
    pub spec: ::core::option::Option<WorkloadSpec>,
}
/// WorkloadList contains a list of Workload resources.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkloadList {
    /// Standard list metadata.
    ///
    /// +optional
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<super::super::super::apimachinery::pkg::apis::meta::v1::ListMeta>,
    /// Items is the list of Workloads.
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<Workload>,
}
/// WorkloadPodGroupTemplateReference references the PodGroupTemplate within the Workload object.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct WorkloadPodGroupTemplateReference {
    /// WorkloadName defines the name of the Workload object.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-long-name
    #[prost(string, optional, tag = "1")]
    pub workload_name: ::core::option::Option<::prost::alloc::string::String>,
    /// PodGroupTemplateName defines the PodGroupTemplate name within the Workload object.
    ///
    /// +required
    /// +k8s:required
    /// +k8s:format=k8s-short-name
    #[prost(string, optional, tag = "2")]
    pub pod_group_template_name: ::core::option::Option<::prost::alloc::string::String>,
}
/// WorkloadSpec defines the desired state of a Workload.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WorkloadSpec {
    /// ControllerRef is an optional reference to the controlling object, such as a
    /// Deployment or Job. This field is intended for use by tools like CLIs
    /// to provide a link back to the original workload definition.
    /// This field is immutable.
    ///
    /// +optional
    /// +k8s:optional
    /// +k8s:immutable
    #[prost(message, optional, tag = "1")]
    pub controller_ref: ::core::option::Option<TypedLocalObjectReference>,
    /// PodGroupTemplates is the list of templates that make up the Workload.
    /// The maximum number of templates is 8. This field is immutable.
    ///
    /// +required
    /// +listType=map
    /// +listMapKey=name
    /// +k8s:required
    /// +k8s:listType=map
    /// +k8s:listMapKey=name
    /// +k8s:maxItems=8
    /// +k8s:immutable
    #[prost(message, repeated, tag = "2")]
    pub pod_group_templates: ::prost::alloc::vec::Vec<PodGroupTemplate>,
}

impl crate::Resource for PodGroup {
    const API_VERSION: &'static str = "scheduling.k8s.io/v1alpha2";
    const GROUP: &'static str = "scheduling.k8s.io";
    const VERSION: &'static str = "v1alpha2";
    const KIND: &'static str = "PodGroup";
    const URL_PATH_SEGMENT: &'static str = "podgroups";
    type Scope = crate::NamespaceResourceScope;
}
impl crate::Metadata for PodGroup {
    type Ty = crate::apimachinery::pkg::apis::meta::v1::ObjectMeta;
    fn metadata(&self) -> Option<&<Self as crate::Metadata>::Ty> {
        self.metadata.as_ref()
    }
    fn metadata_mut(&mut self) -> Option<&mut <Self as crate::Metadata>::Ty> {
        self.metadata.as_mut()
    }
}
impl crate::HasSpec for PodGroup {
    type Spec = crate::api::scheduling::v1alpha2::PodGroupSpec;
    fn spec(&self) -> Option<&<Self as crate::HasSpec>::Spec> {
        self.spec.as_ref()
    }
    fn spec_mut(&mut self) -> Option<&mut <Self as crate::HasSpec>::Spec> {
        self.spec.as_mut()
    }
}
impl crate::HasStatus for PodGroup {
    type Status = crate::api::scheduling::v1alpha2::PodGroupStatus;
    fn status(&self) -> Option<&<Self as crate::HasStatus>::Status> {
        self.status.as_ref()
    }
    fn status_mut(&mut self) -> Option<&mut <Self as crate::HasStatus>::Status> {
        self.status.as_mut()
    }
}
impl crate::HasConditions for PodGroup {
    type Condition = crate::apimachinery::pkg::apis::meta::v1::Condition;
    fn conditions(&self) -> Option<&[<Self as crate::HasConditions>::Condition]> {
        self.status.as_ref().map(|s| s.conditions.as_slice())
    }
    fn conditions_mut(&mut self) -> Option<&mut Vec<<Self as crate::HasConditions>::Condition>> {
        self.status.as_mut().and_then(|s| Some(s.conditions.as_mut()))
    }
}

impl crate::Resource for Workload {
    const API_VERSION: &'static str = "scheduling.k8s.io/v1alpha2";
    const GROUP: &'static str = "scheduling.k8s.io";
    const VERSION: &'static str = "v1alpha2";
    const KIND: &'static str = "Workload";
    const URL_PATH_SEGMENT: &'static str = "workloads";
    type Scope = crate::NamespaceResourceScope;
}
impl crate::Metadata for Workload {
    type Ty = crate::apimachinery::pkg::apis::meta::v1::ObjectMeta;
    fn metadata(&self) -> Option<&<Self as crate::Metadata>::Ty> {
        self.metadata.as_ref()
    }
    fn metadata_mut(&mut self) -> Option<&mut <Self as crate::Metadata>::Ty> {
        self.metadata.as_mut()
    }
}
impl crate::HasSpec for Workload {
    type Spec = crate::api::scheduling::v1alpha2::WorkloadSpec;
    fn spec(&self) -> Option<&<Self as crate::HasSpec>::Spec> {
        self.spec.as_ref()
    }
    fn spec_mut(&mut self) -> Option<&mut <Self as crate::HasSpec>::Spec> {
        self.spec.as_mut()
    }
}
