// This file is @generated by prost-build.
/// MetricListOptions is used to select metrics by their label selectors
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricListOptions {
    /// A selector to restrict the list of returned objects by their labels.
    /// Defaults to everything.
    /// +optional
    #[prost(string, optional, tag = "1")]
    pub label_selector: ::core::option::Option<::prost::alloc::string::String>,
    /// A selector to restrict the list of returned metrics by their labels
    /// +optional
    #[prost(string, optional, tag = "2")]
    pub metric_label_selector: ::core::option::Option<::prost::alloc::string::String>,
}
/// MetricValue is a metric value for some object
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricValue {
    /// a reference to the described object
    #[prost(message, optional, tag = "1")]
    pub described_object: ::core::option::Option<
        super::super::super::super::super::api::core::v1::ObjectReference,
    >,
    /// the name of the metric
    #[prost(string, optional, tag = "2")]
    pub metric_name: ::core::option::Option<::prost::alloc::string::String>,
    /// indicates the time at which the metrics were produced
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<
        super::super::super::super::super::apimachinery::pkg::apis::meta::v1::Time,
    >,
    /// indicates the window (\[Timestamp-Window, Timestamp\]) from
    /// which these metrics were calculated, when returning rate
    /// metrics calculated from cumulative metrics (or zero for
    /// non-calculated instantaneous metrics).
    #[prost(int64, optional, tag = "4")]
    pub window: ::core::option::Option<i64>,
    /// the value of the metric for this
    #[prost(message, optional, tag = "5")]
    pub value: ::core::option::Option<
        super::super::super::super::super::apimachinery::pkg::api::resource::Quantity,
    >,
    /// selector represents the label selector that could be used to select
    /// this metric, and will generally just be the selector passed in to
    /// the query used to fetch this metric.
    /// When left blank, only the metric's Name will be used to gather metrics.
    /// +optional
    #[prost(message, optional, tag = "6")]
    pub selector: ::core::option::Option<
        super::super::super::super::super::apimachinery::pkg::apis::meta::v1::LabelSelector,
    >,
}
/// MetricValueList is a list of values for a given metric for some set of objects
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricValueList {
    #[prost(message, optional, tag = "1")]
    pub metadata: ::core::option::Option<
        super::super::super::super::super::apimachinery::pkg::apis::meta::v1::ListMeta,
    >,
    /// the value of the metric across the described objects
    #[prost(message, repeated, tag = "2")]
    pub items: ::prost::alloc::vec::Vec<MetricValue>,
}
